name: first simple project
on: 
  push:
      branch: main
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: print greeting
        run: echo "good morning"
      - name: print good bye
        run: |
          echo "bye bye"
          ls -lrt
          cat /proc/version
          cat /etc/os-release
      - name: output of github context
        run: echo "${{toJSON(github)}}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
       
      - name: check aws version........"
        run: aws --version

      #AWS
      - name: aws credentials Setup
        uses:  aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1

      - name : create iam User
        run: | 
             pwd
             terraform init
             terraform plan
             echo "check aws version........"
             aws --version
      - name: terraform apply
        #if: github.ref == 'refs/heads/"testenv"' && github.event_name == 'push'
        run: terraform apply -auto-approve


          
             
 
