name: first simple project
on: 
  workflow_dispatch:
    inputs:
      target_environment: 
        type: environment
        description: select the environment
        required: true
        default: dev
env:  
  access_id: ${{ dev.vars.AWS_ACCESS_KEY_ID}}
  access_key: ${{ dev.vars.AWS_SECRET_ACCESS_KEY }}
  environment: "dev"
  

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: print greeting
        run: echo "good morning"
      - name: print good bye
        run: |
          echo "bye bye"
          ls -lrt
          cat /proc/version
          cat /etc/os-release
      - name: output of github context
        run: echo "${{toJSON(github)}}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
       
      - name: check aws version........"
        run: |
            aws --version
            echo "access key ${{ env.access_id }}"
           

      #AWS
      - name: aws credentials Setup
        uses:  aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ env.access_id }}
          aws-secret-access-key: ${{ env.access_key }}
          aws-region: ${{ vars.AWS_REGION }}

      - name : create iam User
        run: | 
             pwd
             terraform init
             terraform plan
             echo "check aws version........"
             aws --version
      - name: terraform apply
        #if: github.ref == 'refs/heads/"testenv"' && github.event_name == 'push'
        run: terraform apply -auto-approve


          
             
 
