name: first simple project
on: 
  workflow_dispatch:
    inputs:
      target_environment: 
        type: environment
        description: select the environment
        required: true
        default: dev
  
jobs:
    my_first_java_project:
      runs-on: ubuntu-latest
      environment: dev
      steps:

          - name: aws credentials Setup using repositiry level variable and secrets
            uses:  aws-actions/configure-aws-credentials@v4
            with: 
              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}

          - name: Checkout Repository 
            uses: actions/checkout@v4
            with: 
                repository: sh378269/simple-java-maven-app

          - name: checking repo content
            run: |
                pwd
                ls -lrt
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1

          - name: Set up Maven
            uses: stCarolas/setup-maven@v5
            with:
              maven-version: 3.9.2

          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'adopt'

          - name: check maven and java version 
            run: |
                java --version
                mvn -v
          - name: maven build
            run: |
                pwd
                mvn -B -DskipTests clean package
                ls -lrt

          - name: build test
            run: |
                mvn test
                cd target
                ls -lrt
                java -jar my-app-1.0-SNAPSHOT.jar
        

          




  