name: first simple project
on: 
  workflow_dispatch:
    inputs:
      target_environment: 
        type: environment
        description: select the environment
        required: true
        default: dev
env:
 ECR_TAG: ${{ github.event.repository.name }}
 ENV_NAME: ${{ inputs.target_environment }}


jobs:
    my_first_java_project:
      runs-on: ubuntu-latest
      environment: dev
      steps:

          - name: aws credentials Setup using repositiry level variable and secrets
            uses:  aws-actions/configure-aws-credentials@v4
            with: 
              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
          
          - name: Checkout Repository 
            uses: actions/checkout@v4

        #  - name: Checkout Repository 
        #    uses: actions/checkout@v4
        #    with: 
        #        repository: sh378269/simple-java-maven-app

          - name: setting repo name
            run: |
                echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
                cat $GITHUB_ENV
          - name: setting ECR variable
            run: 
              echo "ECR_ARN=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-central-1.amazonaws.com" >> $GITHUB_ENV
              cat $GITHUB_ENV

          - name: creating s3 bucket
            run: |
                cd ./.github/workflows/S3
                terraform init
                terraform plan
                terraform apply --auto-approve

          - name: creating ECR and cloudwatch
            run: |
                cd ./.github/workflows
                ls -a
                echo "creating ${{ env.ECR_TAG }} ECR and CloudWatch in ${{ env.ENV_NAME }} env AWS account"
                terraform init -backend-config=bucket=registr-infra-tf-state-${{ inputs.ENV_NAME }} -backend-config=key=config=ecr-repo/${{ env.ECR_TAG }}.tfstate
                terraform plan -var=shared_state_bucket=registr-infra-tf-state-${{ env.ENV_NAME }} -var=app_name=${{ env.ECR_TAG }} -var=market_name=${{ vars.MARKET_NAME }}
                terraform apply -var=shared_state_bucket=registr-infra-tf-state-${{ env.ENV_NAME }} -var=app_name=${{ env.ECR_TAG }} -var=market_name=${{ vars.MARKET_NAME }} --auto-approve

        
          - name: checking repo content
            run: |
                pwd
                ls -lrt

          - name: Set up Maven
            uses: stCarolas/setup-maven@v5
            with:
              maven-version: 3.9.2

          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'adopt'

