name: first simple project
on: 
  workflow_dispatch:
    inputs:
      target_environment: 
        type: environment
        description: select the environment
        required: true
        default: dev
env:
 ECR_TAG: ${{ github.event.repository.name }}
 ENV_NAME: ${{ inputs.target_environment }}


jobs:
    my_first_java_project:
      runs-on: ubuntu-latest
      environment: dev
      steps:

          - name: aws credentials Setup using repositiry level variable and secrets
            uses:  aws-actions/configure-aws-credentials@v4
            with: 
              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
          
          - name: Checkout Repository 
            uses: actions/checkout@v4

        #  - name: Checkout Repository 
        #    uses: actions/checkout@v4
        #    with: 
        #        repository: sh378269/simple-java-maven-app

          - name: setting repo name
            run: |
                echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
                cat $GITHUB_ENV
          - name: setting ECR variable
            run: |
              echo "ECR_ARN=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-central-1.amazonaws.com" >> $GITHUB_ENV
              echo "ECR_STATUS=$(aws ecr describe-repositories --query 'repositories[0].repositoryName' --region ${{ vars.AWS_REGION }})" >> $GITHUB_ENV
              cat $GITHUB_ENV

          - name: Checkout Repository 
            uses: actions/checkout@v4
            with: 
             repository: sh378269/simple-java-maven-app

          - name: Set up Maven
            uses: stCarolas/setup-maven@v5
            with:
              maven-version: 3.9.2

          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'adopt'

          - name: maven build
            run: |
              pwd
              mvn -B -DskipTests clean package
              ls -lrt
              cd target
              ls -lrt

          - name: Build Docker
            run: |
              pwd
              ls -lrt
              docker --version
              docker buildx build -t my-java-image .
              ls -lrt
              docker images
              docker run --name my-java-container -d my-java-image
              docker ps -a

          - name: Push docker image to ECR # Below complete cmd we can get from ECR, login to ECR repo go to repo click on view push command and can get all these details
            run: |
         
                aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 789725493949.dkr.ecr.eu-central-1.amazonaws.com

                docker tag my-java-image:java:1.0 789725493949.dkr.ecr.eu-central-1.amazonaws.com/terraform-project2:java:1.0

                docker push 789725493949.dkr.ecr.eu-central-1.amazonaws.com/terraform-project2:java:1.0


          
          # - name: creating ECR and S3
          #   run: |
          #       cd ./.github/workflows
          #       ls -a
          #       echo "creating ${{ env.ECR_TAG }} ECR and CloudWatch in ${{ env.ENV_NAME }} env AWS account"
          #        terraform init
          #        echo " checking state file before execution"
          #        ls -lrt
          #        terraform plan  
          #        terraform apply --auto-approve
          #        echo " checking content " 
          #        ls -lrt
  
          
